name: remark-lint-link-text
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      # Set up Node.js environment using the specified versions
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run tests
        run: npm test